/**
 * Deelt elke autocomplete-aanvulling (raw.json) in: KOPER, INFO, ANDER, JUNK.
 *   KOPER  wil een aannemer of een prijs voor de renovatie/verbouwing van een woning (ook appartement, rijwoning, villa, hoeve)
 *   INFO   weetjes, regels, premie/btw/lening, doe-het-zelf, betekenis, inspiratie, twijfel (renoveren of afbreken)
 *   ANDER  ander vak (badkamer, keuken, dak, gevel, schilder, architect, ...), ander type (kantoor, winkel, kerk,
 *          appartementsgebouw, vakantiewoning, caravan), merknaam van een concurrent, buitenland
 *   JUNK   vacatures, opleiding, tv/youtube, tweedehands, vastgoed te koop/te huur, vertaling, ongerelateerd
 * INFO met koopnabij=true: premie, btw, epc of renovatieplicht bij de renovatie van een woning. bouw.cjs houdt die
 * zoekers bewust (KOPER-lijst: "renovatie woning 6 btw", "woning renoveren premie"), dus die tellen mee in de blokkeertoets.
 *
 * Regels in volgorde; de eerste treffer wint. HAND = handmatige beslissing per aanvulling (na lezing van de lijst).
 * Exporteert deel(tekst) -> { klasse, reden, koopnabij, geo }.
 */
const W = (s) => new RegExp(`(^|\\s)(${s})(\\s|$)`, 'i');

/* Werkgebied: arrondissementen Antwerpen en Mechelen + Beveren-Kruibeke-Zwijndrecht, zonder de stad Antwerpen en Borsbeek. */
const WERKGEBIED = 'aartselaar|boechout|boom|brasschaat|brecht|edegem|essen|hemiksem|hove|kalmthout|kapellen|kontich|lint|malle|mortsel|niel|ranst|rumst|schelle|schilde|schoten|stabroek|wijnegem|wommelgem|wuustwezel|zandhoven|zoersel|zwijndrecht|berlaar|bonheiden|bornem|duffel|heist op den berg|heist-op-den-berg|lier|mechelen|nijlen|puurs|putte|sint katelijne waver|sint-katelijne-waver|willebroek|blaasveld|tisselt|heindonk|leest|beveren|kruibeke|rupelstreek';
const ANTWERPEN = 'antwerpen|ekeren|wilrijk|deurne|merksem|hoboken|berchem';
const ELDERS_BE = 'gent|brugge|leuven|hasselt|genk|limburg|limburg belgie|west vlaanderen|west-vlaanderen|oost vlaanderen|oost-vlaanderen|vlaams brabant|brabant|kortrijk|oostende|knokke|knokke heist|blankenberge|nieuwpoort|koksijde|middelkerke|de haan|de panne|oostduinkerke|diksmuide|veurne|ieper|poperinge|roeselare|izegem|menen|wevelgem|zwevegem|harelbeke|waregem|tielt|torhout|gistel|zedelgem|oostkamp|maldegem|eeklo|deinze|evergem|lochristi|merelbeke|wetteren|lede|aalst|regio aalst|ninove|geraardsbergen|oudenaarde|ronse|zottegem|denderleeuw|dendermonde|lokeren|sint niklaas|stekene|waasland|temse|dilbeek|halle|ternat|londerzeel|grimbergen|kapelle op den bos|tienen|aarschot|diest|sint truiden|tongeren|bilzen|pelt|lommel|mol|geel|herentals|turnhout|westerlo|kempen|brussel|regio kortrijk|zemst|kerksken|zwartberg|kust|zee|aan zee|ardennen|wallonie';
const BUITENLAND = 'amsterdam|rotterdam|den haag|utrecht|haarlem|leiden|eindhoven|enschede|groningen|friesland|zeeland|arnhem|hoorn|yerseke|ypenburg|zuid holland|midden nederland|nederland|nederlands|spanje|frankrijk|italie|duitsland|curacao|suriname|ibiza|kerkrade|medemblik|elburg|kampen|beilen|veendam|echt susteren|roermond|mariahoeve|dukenburg|etten leur|overvecht|kortenhoef|zuidland|ymere';

function geo(t) {
  if (W(BUITENLAND).test(t)) return 'buitenland';
  if (W(WERKGEBIED).test(t)) return 'werkgebied';
  if (W(ANTWERPEN).test(t)) return 'antwerpen (stad uitgesloten; regionaam)';
  if (W(ELDERS_BE).test(t)) return 'elders in Belgie';
  return '';
}

/* Merknamen en persoonsnamen van concurrenten die in de aanvullingen staan. */
const CONCURRENT = 'chrisma|franssen|noterman|rinovato|george|iha|jvr|mitch|mh|mortier|nn|ooms|schipper|tifre|zedreno|genki|x2o|vermeulen|vanoverbeke|victor|tim|olivier|rh|aj|vdb|decock|claude|vd&k|jk|philips|lucas|b & g|b&g|mario|horst|renovatiedirect|vds|mvh|martlé|gevaert|rl|jb|j\\.b\\.|posthumus|rietveld|pc schilderwerken|ncs|a&r|sf|van marcke|westra|winkeler|renofix|hornbach|duurzame woning renovatie nederland';

const HAND = {
  // KOPER: aannemer/prijs/renovatie van een woning, na lezing
  'huis renoveren': ['KOPER', 'renovatie woning (hoofdterm)'],
  'woning renoveren': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renovatie woning': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renovatie huis': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renoveren huis': ['KOPER', 'renovatie woning (hoofdterm)'],
  'woning renovatie': ['KOPER', 'renovatie woning (hoofdterm)'],
  'woningrenovatie': ['KOPER', 'renovatie woning (hoofdterm)'],
  'woningrenovaties': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renovatie van een woning': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renovatie van woning': ['KOPER', 'renovatie woning (hoofdterm)'],
  'renovatie woning huis': ['KOPER', 'renovatie woning'],
  'renovatie woning woning': ['KOPER', 'renovatie woning'],
  'renovatie woning en woning': ['KOPER', 'renovatie woning'],
  'renovatie woning renoveren': ['KOPER', 'renovatie woning'],
  'huis renoveren woning': ['KOPER', 'renovatie woning'],
  'huis renoveren huis': ['KOPER', 'renovatie woning'],
  'huis renoveren renovatie': ['KOPER', 'renovatie woning'],
  'renovatie bestaande ́woning': ['KOPER', 'renovatie woning'],
  'je huis renoveren': ['KOPER', 'renovatie woning'],
  'mijn huis renoveren': ['KOPER', 'renovatie woning'],
  'huis binnen renoveren': ['KOPER', 'renovatie woning (binnenkant)'],
  'huis renoveren particulier': ['KOPER', 'particulier zoekt renovatie'],
  'renovatie woning particulier': ['KOPER', 'particulier zoekt renovatie'],
  'renovatie aannemer particulier': ['KOPER', 'particulier zoekt aannemer'],
  'totaalrenovatie': ['KOPER', 'totaalrenovatie (hoofdterm)'],
  'totaalrenovaties': ['KOPER', 'totaalrenovatie (hoofdterm)'],
  'totaalrenovatie project': ['KOPER', 'totaalrenovatie'],
  'totaalrenovatie consult': ['KOPER', 'totaalrenovatie: advies/gesprek'],
  'totaalrenovatie van a tot z': ['KOPER', 'totaalrenovatie'],
  'totaalrenovatie xl': ['KOPER', 'totaalrenovatie'],
  'totaalrenovatie of totaalrenovatie': ['KOPER', 'totaalrenovatie'],
  'totaalrenovatie budget': ['KOPER', 'prijs'],
  'huis renoveren budget': ['KOPER', 'prijs'],
  'totaalrenovatie quote': ['KOPER', 'offerte (Engels woord)'],
  'renovatie aannemer quote': ['KOPER', 'offerte (Engels woord)'],
  'renovatie aannemer aanvragen': ['KOPER', 'aannemer'],
  'renovatie woning aanvragen': ['KOPER', 'renovatie aanvragen'],
  'renovatie aannemer aan huis': ['KOPER', 'aannemer'],
  'renovatie aannemer renovatie': ['KOPER', 'aannemer'],
  'renovatie aannemer maken': ['KOPER', 'aannemer'],
  'renovatie woning maken': ['KOPER', 'renovatie woning'],
  'renovatie aannemer plaatsen': ['KOPER', 'aannemer'],
  'renovatie aannemer herstellen': ['KOPER', 'aannemer'],
  'renovatie aannemer onderhoud': ['KOPER', 'aannemer'],
  'renovatie woning onderhoud': ['KOPER', 'renovatie woning'],
  'renovatie aannemer nv': ['KOPER', 'aannemer'],
  'renovatie aannemer epc': ['KOPER', 'aannemer voor epc-renovatie'],
  'aannemer zoeken renovatie': ['KOPER', 'aannemer'],
  'renovatie woning zoeken': ['KOPER', 'renovatie woning'],
  'renovatie woning opzoeken': ['KOPER', 'renovatie woning'],
  'renovatie woning laten plaatsen': ['KOPER', 'renovatie laten uitvoeren'],
  'renovatie woning inrichten': ['KOPER', 'renovatie woning'],
  'renovatie aannemer inrichten': ['KOPER', 'aannemer'],
  'renovatie woning uitbreiden': ['KOPER', 'verbouwing woning (uitbreiding)'],
  'renovatie uitbouw woning': ['KOPER', 'verbouwing woning (uitbouw)'],
  'renovatie achterbouw rijwoning': ['KOPER', 'verbouwing woning (achterbouw)'],
  'totaalrenovatie benedenverdieping': ['KOPER', 'renovatie gelijkvloers (LP-keuze)'],
  'aannemer renovatie 1e verdieping inclusief badkamer': ['KOPER', 'renovatie verdieping (LP-keuze)'],
  'totaalrenovatie interieur': ['KOPER', 'renovatie binnenkant woning'],
  'renovatie woning nieuwbouw': ['KOPER', 'aannemer renovatie/nieuwbouw'],
  'renovatie aannemer nieuwbouw': ['KOPER', 'aannemer renovatie/nieuwbouw'],
  'aannemer': ['KOPER', 'aannemer gezocht (vak niet genoemd)'],
  'aannemers': ['KOPER', 'aannemer gezocht (vak niet genoemd)'],
  'aannemer in de buurt': ['KOPER', 'aannemer gezocht (vak niet genoemd)'],
  'aannemers in de buurt': ['KOPER', 'aannemer gezocht (vak niet genoemd)'],
  'algemene aannemer': ['KOPER', 'aannemer gezocht (vak niet genoemd)'],
  'aannemer voor renovatie': ['KOPER', 'aannemer renovatie'],
  'totaalrenovatie bedrijf': ['KOPER', 'renovatiebedrijf'],
  'totaalrenovatie firma': ['KOPER', 'renovatiebedrijf'],
  'totaalrenovatie centrum': ['KOPER', 'renovatiebedrijf'],
  'woning renovatie bedrijven': ['KOPER', 'renovatiebedrijf'],
  'huis renoveren bedrijf': ['KOPER', 'renovatiebedrijf'],
  'renovatiewerken': ['KOPER', 'renovatiewerken (algemeen)'],
  'verbouwingswerken': ['KOPER', 'verbouwing (algemeen)'],
  'huis laten renoveren': ['KOPER', 'laten renoveren'],
  'huis volledig laten renoveren': ['KOPER', 'laten renoveren'],
  'je huis laten renoveren': ['KOPER', 'laten renoveren'],
  'huis renoveren plan': ['KOPER', 'renovatie woning'],
  'renovatie woning regio willebroek': ['KOPER', 'renovatie woning + plaats'],
  'renovatie aannemer regio willebroek': ['KOPER', 'aannemer + plaats'],
  'renovatie aannemer loods': ['ANDER', 'ander type: loods'],
  'totaalrenovatie energiescanner': ['ANDER', 'energiescan'],
  'huis renoveren energiescanner': ['ANDER', 'energiescan'],
  'hoe renovatiekosten berekenen': ['KOPER', 'prijs berekenen (calculator op de LP)'],
  'renovatiekosten inschatten': ['KOPER', 'prijs'],
  'renovatiekosten schatten': ['KOPER', 'prijs'],
  'renovatiekosten': ['KOPER', 'prijs'],
  'renovatie woning uren': ['KOPER', 'prijs (uren)'],
  'm3 prijs verbouwing': ['KOPER', 'prijs'],
  'renovatie woning quick': ['JUNK', 'onduidelijk'],
  // INFO
  'renovatie': ['INFO', 'te algemeen: geen koop- of woningsignaal'],
  'renoveren': ['INFO', 'te algemeen: geen koop- of woningsignaal'],
  'renoverend': ['JUNK', 'woordvorm'],
  'verbouwing': ['INFO', 'te algemeen: geen koop- of woningsignaal'],
  'verbouwingen': ['INFO', 'te algemeen: geen koop- of woningsignaal'],
  'verbouwen': ['INFO', 'te algemeen: geen koop- of woningsignaal'],
  'huis verbouwen': ['KOPER', 'verbouwing woning (hoofdterm)'],
  'woning verbouwen': ['KOPER', 'verbouwing woning (hoofdterm)'],
  'oude woning': ['INFO', 'te algemeen'],
  'huis gekocht': ['INFO', 'te algemeen'],
  'huis gekocht wat nu': ['INFO', 'weetje'],
  'renovatie woning eigendom': ['INFO', 'weetje'],
  'renovatie woning uitbetaling': ['INFO', 'weetje'],
  'renovatie aannemer uitbetaling': ['INFO', 'weetje'],
  'renovatie woning ruilen': ['INFO', 'weetje'],
  'renovatie woning co-ouderschap': ['INFO', 'weetje'],
  'renovatie woning co2': ['INFO', 'weetje'],
  'renovatie woning heffen': ['INFO', 'weetje'],
  'huis renoveren heffen': ['INFO', 'weetje'],
  'renovatie aannemer heffen': ['INFO', 'weetje'],
  'huis renoveren doorgeven': ['INFO', 'weetje'],
  'huis renoveren document': ['INFO', 'weetje'],
  'huis renoveren checken': ['INFO', 'weetje'],
  'huis renoveren mogelijkheden': ['INFO', 'weetje'],
  'huis renoveren uitleg': ['INFO', 'weetje'],
  'renovatie aannemer uitleg': ['INFO', 'weetje'],
  'renovatie aannemer voorbeeld': ['INFO', 'weetje'],
  'huis renoveren zonder afspraak': ['INFO', 'weetje'],
  'renovatie aannemer zelfstandige': ['INFO', 'weetje (zelfstandige worden)'],
  'renovatie woning zelfstandige': ['INFO', 'weetje (zelfstandige worden)'],
  'totaalrenovatie zelfstandige': ['INFO', 'weetje (zelfstandige worden)'],
  'renovatie aannemer kopen': ['INFO', 'onduidelijk: bedrijf overnemen'],
  'renovatie aannemer kosten': ['KOPER', 'prijs'],
  'totaalrenovatie cm': ['JUNK', 'onduidelijk (CM)'],
  'renovatie woning cm': ['JUNK', 'onduidelijk (CM)'],
  'renovatie aannemer cm': ['JUNK', 'onduidelijk (CM)'],
  'totaalrenovatie familie': ['JUNK', 'onduidelijk'],
  'totaalrenovatie fortis': ['JUNK', 'onduidelijk (bank)'],
  'totaalrenovatie you': ['JUNK', 'youtube'],
  'huis renoveren quotes': ['JUNK', 'citaten'],
  'huis renoveren quote 500': ['JUNK', 'onduidelijk'],
  'huis renoveren xl': ['JUNK', 'onduidelijk'],
  'renovatie woning xl': ['JUNK', 'onduidelijk'],
  'renovatie woning xxl': ['JUNK', 'onduidelijk'],
  'renovatie aannemer xl': ['JUNK', 'onduidelijk'],
  'renovatie aannemer xls': ['INFO', 'excel-sjabloon'],
  'renovatie woning yuki': ['JUNK', 'boekhoudsoftware'],
  'renovatie woning quotes': ['JUNK', 'citaten'],
  'renovatie woning ypres': ['ANDER', 'elders (Ieper, Engels)'],
  'huis renoveren camper': ['JUNK', 'camper'],
  'huis renoveren cadeau': ['JUNK', 'cadeau'],
  'huis renoveren cadgis': ['INFO', 'kaartviewer'],
  'huis renoveren buitenkant': ['ANDER', 'buitenkant (gevel/dak)'],
  'huis muren renoveren': ['ANDER', 'deelwerk: muren'],
  'houten huis renoveren': ['KOPER', 'renovatie woning (houten huis)'],
  'huis zonder fundering renoveren': ['INFO', 'weetje (fundering)'],
  'huis renoveren verwarming': ['ANDER', 'ander vak: verwarming'],
  'warmtepomp renovatie woning': ['ANDER', 'ander vak: warmtepomp'],
  'ventilatie renovatie woning': ['ANDER', 'ander vak: ventilatie'],
  'renovatie aannemer elektriciteit': ['ANDER', 'ander vak: elektriciteit'],
  'renovatie aannemer zonnepanelen': ['ANDER', 'ander vak: zonnepanelen'],
  'totaalrenovatie zonnepanelen': ['ANDER', 'ander vak: zonnepanelen'],
  'aannemer ruwbouw renovatie': ['KOPER', 'aannemer renovatie (ruwbouw)'],
  'aannemer volledige renovatie': ['KOPER', 'aannemer volledige renovatie'],
  'totaalrenovatie in willebroek': ['KOPER', 'totaalrenovatie + plaats'],
  'totaalrenovatie in boom': ['KOPER', 'totaalrenovatie + plaats'],
  'renovatie woning huren': ['JUNK', 'vastgoed huur'],
  'renovatie aannemer huren': ['JUNK', 'onduidelijk (huren)'],
  'huis renoveren huur': ['JUNK', 'vastgoed huur'],
  'renovatie woning te huur': ['JUNK', 'vastgoed huur'],
  'renovatie aannemer te huur': ['JUNK', 'vastgoed huur'],
  'renovatie aannemer te koop': ['JUNK', 'vastgoed te koop'],
  'renovatie woning rechten huurder': ['INFO', 'huurder'],
  'renovatie verhuurde woning': ['INFO', 'huurder/verhuurder'],
  'klachten renovatie huurwoning': ['INFO', 'huurder'],
  'renovatie woning normen': ['INFO', 'regels'],
  'renovatie aannemer verplicht': ['INFO', 'regels'],
  'huis verplicht renoveren': ['INFO', 'renovatieplicht', true],
  'renovatie verplicht bij woning die je koopt of erft': ['INFO', 'renovatieplicht', true],
  'huis renoveren epc f': ['KOPER', 'woning met slecht EPC-label moet renoveren (bouw.cjs KOPER: "renovatie woning epc label")'],
  'renoveren huis epc waarde': ['INFO', 'epc-waarde', true],
  'renovatie woning ouder dan 10 jaar': ['INFO', 'btw 6% (woning ouder dan 10 jaar)', true],
  'renovatie woning 6 btw': ['INFO', 'btw 6%', true],
  'renovatie woning 9 btw': ['INFO', 'btw', true],
  'renovatie oude woning btw': ['INFO', 'btw', true],
  'renovatie woning btw tarief': ['INFO', 'btw', true],
  'huis renoveren btw': ['INFO', 'btw', true],
  'renovatie huis btw': ['INFO', 'btw', true],
  'verbouwing 6 btw': ['INFO', 'btw', true],
  'verbouwen aan 6 btw': ['INFO', 'btw', true],
  'btw renovatie tweede woning': ['INFO', 'btw', true],
  '6 btw renovatie doe het zelf': ['INFO', 'btw + doe-het-zelf'],
  'btw tarief renovatie woning nederland': ['ANDER', 'buitenland'],
  'renovatie woning gemeente willebroek': ['INFO', 'gemeente (premie/regels)'],
  'huis renoveren gemeente willebroek': ['INFO', 'gemeente (premie/regels)'],
  'huis renoveren gemeente kapelle op den bos': ['INFO', 'gemeente (premie/regels)'],
  'renovatie aannemer gemeente willebroek': ['INFO', 'gemeente (premie/regels)'],
  'totaalrenovatie gemeente willebroek': ['INFO', 'gemeente (premie/regels)'],
  'totaalrenovatie gemeente boom': ['INFO', 'gemeente (premie/regels)'],
  'huis renoveren stad mechelen': ['INFO', 'stad (premie/regels)'],
  'huis renoveren ugc mechelen': ['JUNK', 'onduidelijk'],
  'huis renoveren ugc': ['JUNK', 'onduidelijk'],
  'huis renoveren q8': ['JUNK', 'tankstation'],
  'huis renoveren q8 willebroek': ['JUNK', 'tankstation'],
  'renovatie aannemer q8': ['JUNK', 'tankstation'],
  'totaalrenovatie tuin': ['ANDER', 'deelwerk: tuin'],
  'energetische totaalrenovatie': ['KOPER', 'energetische renovatie woning'],
  'aannemer energetische renovatie': ['KOPER', 'aannemer energetische renovatie'],
  'grote renovatie woning': ['KOPER', 'grote renovatie woning'],
  'renovatie woning duurtijd': ['INFO', 'duurtijd'],
  'totaalrenovatie duurtijd': ['INFO', 'duurtijd'],
  'hoeveel tijd om huis te renoveren': ['INFO', 'duurtijd'],
  'totaalrenovatie hoe beginnen': ['INFO', 'waar beginnen'],
  'wat is totaalrenovatie': ['INFO', 'betekenis'],
  'huis renoveren wat is dat': ['INFO', 'betekenis'],
  'totaalrenovatie ervaringen': ['INFO', 'ervaringen'],
  'totaalrenovatie reddit': ['INFO', 'forum'],
  'totaalrenovatie met architect': ['ANDER', 'architect'],
  'totaalrenovatie zonder architect': ['INFO', 'architect nodig? (regels)'],
  'huis renoveren notaris': ['INFO', 'notaris'],
  'huis renoveren zonder notaris': ['INFO', 'notaris'],
  'totaalrenovatie rijhuis 120m2': ['KOPER', 'totaalrenovatie rijwoning'],
  'renovatie zonevreemde woning': ['INFO', 'regels (zonevreemd)'],
  'geklasseerde woning renoveren': ['INFO', 'regels (erfgoed)'],
  'renovatie woning in willebroek': ['KOPER', 'renovatie woning + plaats'],
  'renovatie woning in boom': ['KOPER', 'renovatie woning + plaats'],
  'renovatie woning in grimbergen': ['KOPER', 'renovatie woning + plaats'],
  'renovatie woning te koop willebroek': ['JUNK', 'vastgoed te koop'],
  'renovatie woning huren willebroek': ['JUNK', 'vastgoed huur'],
  'renovatie woning te huur willebroek': ['JUNK', 'vastgoed huur'],
  'renovatie kleine woning': ['KOPER', 'renovatie woning'],
  'renovatie woning kostprijs': ['KOPER', 'prijs'],
  'totale renovatie woning kostprijs': ['KOPER', 'prijs'],
  'wat kost het om een jaren 70 huis te renoveren': ['KOPER', 'prijs'],
  'renovatie woning jaren 60': ['KOPER', 'renovatie woning (bouwjaar)'],
  'renovatie woning jaren 70': ['KOPER', 'renovatie woning (bouwjaar)'],
  'renovatie woning jaren 50': ['KOPER', 'renovatie woning (bouwjaar)'],
  'renovatie woning juni 2024': ['JUNK', 'onduidelijk'],
  'renovatie landelijke woning': ['KOPER', 'renovatie woning (type)'],
  'renovatie vrijstaande woning': ['KOPER', 'renovatie woning (type)'],
  'renovatie modernistische woning': ['KOPER', 'renovatie woning (type)'],
  'renovatie art deco woning': ['KOPER', 'renovatie woning (type)'],
  'renovatie bel etage woning': ['KOPER', 'renovatie woning (type)'],
  'totaalrenovatie herenhuis': ['KOPER', 'totaalrenovatie (type woning)'],
  'totaalrenovatie villa': ['KOPER', 'totaalrenovatie (type woning)'],
  'totaalrenovatie hoeve': ['KOPER', 'totaalrenovatie (type woning)'],
  'totaalrenovatie rijwoning': ['KOPER', 'totaalrenovatie (type woning)'],
  'totaalrenovatie studio': ['KOPER', 'totaalrenovatie (type woning)'],
  'totaalrenovatie appartement': ['KOPER', 'totaalrenovatie appartement (LP-keuze)'],
  'totaalrenovatie chalet': ['ANDER', 'vakantiewoning'],
  'renovatie appartementsgebouw': ['ANDER', 'appartementsgebouw'],
  'huis renoveren of afbreken': ['INFO', 'twijfel: renoveren of afbreken'],
  'totaalrenovatie aj': ['ANDER', 'concurrent (initialen)'],
  'totaalrenovatie rh': ['ANDER', 'concurrent (initialen)'],
  'totaalrenovatie tim': ['ANDER', 'concurrent (persoonsnaam)'],
  'totaalrenovatie olivier': ['ANDER', 'concurrent (persoonsnaam)'],
  'totaalrenovatie victor': ['ANDER', 'concurrent (victorrenoveert.be)'],
  'totaalrenovatie george': ['ANDER', 'concurrent (persoonsnaam)'],
  'totaalrenovatie vermeulen': ['ANDER', 'concurrent (persoonsnaam)'],
  'totaalrenovatie vanoverbeke': ['ANDER', 'concurrent (persoonsnaam)'],
  'aannemer blind gekocht': ['JUNK', 'onduidelijk'],
  'huis renoveren en doorverkopen': ['INFO', 'investeerder: renoveren en verkopen'],
  'totaalrenovatie slaapkamer': ['ANDER', 'deelwerk: slaapkamer'],
  'totaalrenovatie living': ['ANDER', 'deelwerk: living'],
  'totaalrenovatie zolder': ['ANDER', 'deelwerk: zolder'],
  'renovatie zolder aannemer': ['ANDER', 'deelwerk: zolder'],
  'totaalrenovatie toilet': ['ANDER', 'deelwerk: toilet'],
  'totaalrenovatie ugent': ['JUNK', 'universiteitsgebouw'],
  'huis renoveren ugent': ['JUNK', 'universiteit'],
  'renovatie aannemer ugent': ['JUNK', 'universiteit'],
  'renovatie aannemer cvo': ['JUNK', 'opleiding'],
  'renovatie aannemer condoleren': ['JUNK', 'onduidelijk'],
  'renovatie aannemer regels': ['INFO', 'regels'],
  'renovatie aannemer wetgeving': ['INFO', 'regels'],
  'renovatie aannemer frans': ['JUNK', 'vertaling'],
  'renovatie aannemer fiscaal aftrekbaar': ['INFO', 'fiscaal'],
  'aannemer frans': ['JUNK', 'vertaling'],
  'aannemer engels': ['JUNK', 'vertaling'],
  'aannemer betekenis': ['INFO', 'betekenis'],
  'woning strippen en renoveren belgie': ['KOPER', 'woning strippen en renoveren'],
  'woning strippen en renoveren in willebroek': ['KOPER', 'woning strippen en renoveren + plaats'],
  'renovatie mechelen': ['KOPER', 'renovatie + plaats'],
  'verbouwen op zondag': ['INFO', 'regels'],
  'verbouwen vlaanderen': ['INFO', 'te algemeen'],
  'renovatie smalle rijwoning': ['KOPER', 'renovatie rijwoning'],
  'renovatie kleine rijwoning': ['KOPER', 'renovatie rijwoning'],
  'renovatie wallonie': ['ANDER', 'ander gewest (Wallonie)'],
  'renovatie wallonie 2024': ['ANDER', 'ander gewest (Wallonie)'],
  'charleroi renovaties': ['ANDER', 'ander gewest (Wallonie)'],
  'zwart onderhoud en renovatie': ['ANDER', 'merknaam concurrent'],
  'goedkoop lenen renovatie': ['INFO', 'lening'],
  'in het zwart renovatiewerken': ['JUNK', 'zwartwerk'],
  'huis renoveren wallonie 2024': ['ANDER', 'ander gewest (Wallonie)'],
  'huis renoveren wallonie belgie': ['ANDER', 'ander gewest (Wallonie)'],
  'totaalrenovatie wallonie 2024': ['ANDER', 'ander gewest (Wallonie)'],
  'huis renoveren immo': ['JUNK', 'vastgoed'],
  'woningrenovatie tool': ['INFO', 'tool'],
  'wanneer huis renoveren': ['INFO', 'weetje'],
  'vergoeding renovatie woning': ['INFO', 'weetje (vergoeding)'],
  'huis verbouwen voor een ton': ['INFO', 'weetje'],
  'renovatie goedkoopste woning': ['INFO', 'onduidelijk'],
  'renovatie woning uren': ['INFO', 'onduidelijk'],
  'renovatie woning opzoeken': ['INFO', 'onduidelijk (renovatiedatum opzoeken)'],
  'renovatie woning zoeken': ['INFO', 'onduidelijk (woning zoeken)'],
  'renovatie woning inrichten': ['INFO', 'inrichting'],
  'renovatie woning onderhoud': ['INFO', 'onduidelijk'],
  'huis renoveren plan': ['INFO', 'plan'],
  'renovatie woning nieuwbouw': ['INFO', 'renovatie of nieuwbouw'],
  'renovatie woning aanvragen': ['INFO', 'onduidelijk (premie of vergunning aanvragen)'],
  'huis goedkoop renoveren': ['INFO', 'besparen/tips'],
  'huis renoveren goedkoopste': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'huis renoveren goedkoopste prijs': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'renovatie goedkoopste prijs': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'renovatie goedkoopste': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'totaalrenovatie goedkoopste': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'totaalrenovatie goedkoopste prijs': ['KOPER', 'prijs (goedkoopste: prijsjager)'],
  'totaalrenovatie kerksken': ['KOPER', 'totaalrenovatie + plaats'],
  'totaalrenovatie zwartberg': ['KOPER', 'totaalrenovatie + plaats'],
  'huis gekocht met verborgen gebreken': ['INFO', 'juridisch'],
  'woning verbouwen tot kangoeroewoning': ['INFO', 'regels (kangoeroewoning)'],
  'woning verbouwen in agrarisch gebied': ['INFO', 'regels (agrarisch gebied)'],
};

/* Geordende regels: [klasse, reden, regex, koopnabij?]. De eerste treffer wint. */
const REGELS = [
  // JUNK
  ['JUNK', 'vacature/job', /vacature|\bjobs?\b|jobstudent|flexijob|\bloon(brief|barema)?\b|renovatiecoördinator loon/i],
  ['JUNK', 'opleiding/cursus', /opleiding|cursus|\bstages?\b|\bvdab\b|\bcvo\b|\bnrp\b/i],
  ['JUNK', 'tv/youtube/programma', /programma|youtube|\bvtm\b|qmusic|\bflair\b|schooltv|voor dummies|\bboek\b/i],
  ['JUNK', 'tweedehands', /tweedehands|2dehands/i],
  ['JUNK', 'zwangerschap (strippen)', /zwangerschap|bevalling|\b3[89] weken|\b40 weken/i],
  ['JUNK', 'vertaling/woordspel', /\bengels\b|\bfrans\b|in het engels|9 letters|\bquiz(let)?\b|animal crossing|\bnederlands\b$/i],
  ['JUNK', 'boekhouding', /jaarrekening|activeren\b/i],
  ['JUNK', 'infrastructuur/publiek gebouw', /tunnel|airport|\buz\b|\buza\b|ugent|binnenhof|notre dame|ten bosch|\bbergh\b|gemeentehuis|nederlandsche bank|schoolfeest|schooluren|kerkstraat|kerkhof|kerklaan|kerkweg|kerksken|zwartbroekplein|zwarte woud|zwartberg|marga klompe|mariahoeve|dukenburg|winkelcentrum/i],
  ['JUNK', 'vastgoed te koop/te huur', /te koop|\bte huur\b|immoweb|zimmo|woningen te koop|huis kopen om te renoveren|\bkopen\b.*renoveren en|renovatie (woning|huis|woningen) kopen|renovatie huis kopen|huis renoveren kopen|nederland kopen|oude woning(en)? (kopen|te koop)|huis te renoveren|te renoveren (rijwoning|huis)|appartement te renoveren|huis om te renoveren/i],
  ['JUNK', 'huis gekocht (belasting/feest)', /huis gekocht (programma|proficiat|flair|cadeau|met verborgen|in 2025|belasting|voor huwelijk)/i],
  ['JUNK', 'ongerelateerd', /\bxtc\b|klachtendienst|klachtenformulier|klachtencommissie|zwarte lijst|zwart wit|zwart metaal|\bai\b|met ai|stacaravan|oude woninghuurwet|renovatie tweedehands|tweedehands auto|renovatie woning quiz/i],
  // ANDER: concurrent, buitenland, ander type, ander vak
  ['ANDER', 'merknaam concurrent', new RegExp(`(^|\\s)(${CONCURRENT})(\\s|$)`, 'i')],
  ['ANDER', 'buitenland', W(BUITENLAND)],
  ['ANDER', 'ander type gebouw', /kantoor|winkel|horeca|\bkerk(gebouw)?\b|schoolgebouw|\bschool\b|appartementsgebouw|woningbouw|\bloods\b|chalet|caravan|mobilhome|containerwoning|\bcamper\b|kangoeroewoning|agrarisch/i],
  ['ANDER', 'vakantiewoning/kust', /aan zee|appartement (kust|zee|knokke|nieuwpoort|oostende)|renovatie appartement (kust|zee)|totaalrenovatie appartement (kust|oostende)/i],
  ['ANDER', 'ander vak: badkamer', /badkamer|wellness|doucheput/i],
  ['ANDER', 'ander vak: keuken', /keuken/i],
  ['ANDER', 'ander vak: dak', /(^|\s)dak|dakrenovatie|dakwerk|dakkapel|dakgoot|daktrim|dakplaat|plat dak/i],
  ['ANDER', 'ander vak: gevel', /gevel/i],
  ['ANDER', 'ander vak: schilder/behang/vloer', /schilder|behang|renovatievlies|laminaat|parket|vloer/i],
  ['ANDER', 'ander vak: trap/toilet/tuin/meubel/beslag', /trap|toilet|\bwc\b|tuin|meubel|plint|renovatieput|renovatieschild|kozijn|rooster|scharnier|paumelle|deurbeslag|vensterbank|glas renovatie|ramen/i],
  ['ANDER', 'ander vak: elektriciteit/isolatie/energie', /elektriciteit|isoleren|isolatie|energiescan|warmtepomp|van het gas af|verduurzamen/i],
  ['ANDER', 'ander vak: architect/tekenaar', /architect|tekenaar/i],
  ['ANDER', 'deelwerk: kamer', /slaapkamer|zolder|living/i],
  // INFO
  ['INFO', 'doe-het-zelf', /zelf renoveren|doe[- ]het[- ]zelf|\bzelf\b/i],
  ['INFO', 'premie/subsidie', /premie|subsidie|fluvius/i, true],
  ['INFO', 'renovatieplicht/epc-regel', /renovatieplicht|renovatieverplichting|epc|verplichtingen/i, true],
  ['INFO', 'lening/hypotheek/krediet', /lening|hypothe|krediet|overwaarde|simulatie/i],
  ['INFO', 'btw/fiscaal', /\bbtw\b|fiscaal|aftrekbaar|kadaster|belasting/i],
  ['INFO', 'betekenis/wikipedia', /betekenis|wikipedia|wat is\b/i],
  ['INFO', 'stappenplan/tips/volgorde', /stappenplan|checklist|\btips\b|waar beginnen|hoe beginnen|wat eerst|volgorde|\bplanning\b|\bhoe\b/i],
  ['INFO', 'regels/vergunning', /vergunning|\bregels\b|wetgeving|\bnormen\b|renovatiestandaard|huurder|huurwoning/i],
  ['INFO', 'forum/klachten/ervaringen', /forum|klachten|ervaringen|reviews|failliet|renovatiedirect/i],
  ['INFO', 'inspiratie/voorbeelden', /voor en na|ideeën|voorbeeld|foto's|\bfoto\b|renovatiemarkt/i],
  ['INFO', 'twijfel/investering', /\bof (nieuw ?bouwen|nieuwbouw|afbreken|verkopen|verhuizen|niet|totaalrenovatie)\b|afbreken of|bouwen of renoveren|slopen en nieuwbouwen|en (verkopen|doorverkopen|terug verkopen)|voor verkoop|om te verhuren|voor verhuur|renoveren of nieuwbouw/i],
  ['INFO', 'excel/sjabloon', /excel|\bxls\b|bestek/i],
  ['INFO', 'advies', /^advies /i],
  ['JUNK', 'strippen (niet bouw)', /^strippen$/i],
  ['ANDER', 'ander vak/ander object', /meubel renovatie|traprenovatie/i],
  // KOPER: prijs
  ['KOPER', 'prijs', /prijs|kost|kosten|kostprijs|berekenen|per m2|per m²|budget|offerte|goedkoop|goedkoopste/i],
  // KOPER: aannemer/bedrijf
  ['KOPER', 'aannemer/bedrijf', /aannemer|renovatiebedrijf|bedrijf|firma|aannemers/i],
  // KOPER: renovatie van een woning (+ plaats of type)
  ['KOPER', 'renovatie woning', /totaalrenovatie|woningrenovatie|renovatie (woning|huis|rijwoning|appartement|oude woning|studio)|(huis|woning|appartement|rijwoning|oud huis|hele huis|oude woning) (volledig |compleet |totaal |laten |binnen )?(renoveren|verbouwen|renovatie)|volledige renovatie|renovatie van (een )?woning|verbouwing (huis)?|renovatiewerken|renoveren (huis|brugge|vlaanderen)/i],
];

/* Premie/btw/epc-zoekers met een extra info-woord zijn geen koopnabije zoekers. */
const NIET_KOOPNABIJ = /forum|klachten|wikipedia|checklist|stappenplan|goedkoop|hypothe|wallon|betekenis|charleroi|failliet|lening|krediet|zelf|tweedehands|tekenaar|energiescan|opleiding|cursus|jobs?|loon|stage|mobilhome|caravan|containerwoning|laminaat|behang|parket|schilder|immoweb|zimmo|nederland|te huur|vacature|gemeente|fluvius/i;

function deel(tekst) {
  const t = tekst.toLowerCase().trim();
  const g = geo(t);
  if (HAND[t]) { const [klasse, reden, koopnabij] = HAND[t]; return { klasse, reden, koopnabij: !!koopnabij, geo: g, bron: 'hand' }; }
  for (const [klasse, reden, re, koopnabij] of REGELS) if (re.test(t)) {
    let k = klasse, r = reden;
    // Plaats buiten België is geen koper voor AB; plaats in België blijft koper (geo-veld zegt waar).
    return { klasse: k, reden: r, koopnabij: !!koopnabij && /renover|renovatie|woning|huis|verbouw/.test(t) && !NIET_KOOPNABIJ.test(t), geo: g, bron: 'regel' };
  }
  return { klasse: 'ONBEKEND', reden: '', koopnabij: false, geo: g, bron: 'geen' };
}

module.exports = { deel, geo };
