// Kandidaat-negatives dak-campagne. w = woordgroep (phrase), e = exact, b = breed.
const K = {};
K['1 Kleine klussen (onder 5.000 euro)'] = [
  ['herstellen','w','herstelling, kleine klus'],
  ['herstelling','w','herstelling, kleine klus'],
  ['herstellingen','w','herstelling, kleine klus'],
  ['dakherstelling','w','herstelling, kleine klus'],
  ['dakherstellingen','w','herstelling, kleine klus'],
  ['herstel','w','herstelling, kleine klus'],
  ['repareren','w','reparatie, kleine klus'],
  ['reparatie','w','reparatie, kleine klus'],
  ['reparaties','w','reparatie, kleine klus'],
  ['noodherstelling','w','noodinterventie, kleine klus'],
  ['noodherstel','w','noodinterventie, kleine klus'],
  ['noodgeval','w','noodinterventie, kleine klus'],
  ['dringend','w','spoedklus, geen renovatieproject'],
  ['spoed','w','spoedklus, geen renovatieproject'],
  ['24 uur','w','spoeddienst; ook concurrent Nieuw Dak in 24 uur'],
  ['24/7','w','spoeddienst'],
  ['lek','w','lekzoeker, herstelling'],
  ['lekt','w','lekzoeker, herstelling'],
  ['lekken','w','lekzoeker, herstelling'],
  ['lekkage','w','lekzoeker, herstelling'],
  ['lekkages','w','lekzoeker, herstelling'],
  ['lekkend','w','lekzoeker, herstelling'],
  ['daklek','w','lekzoeker, herstelling'],
  ['daklekkage','w','lekzoeker, herstelling'],
  ['hagel','w','hagelschade, herstelling of auto'],
  ['hagelschade','w','hagelschade, herstelling of auto'],
  ['kleine klus','w','zoekt expliciet kleine klus'],
  ['kleine klussen','w','zoekt expliciet kleine klus'],
  ['kleine werken','w','zoekt expliciet kleine klus'],
  ['klein dakwerk','w','zoekt expliciet kleine klus'],
  ['onderhoud','w','onderhoud, geen vernieuwing'],
  ['onderhoudscontract','w','onderhoud, geen vernieuwing'],
  ['klusjesman','w','kleine klus, klusjesdienst'],
  ['klusser','w','kleine klus, klusjesdienst'],
  ['klusbedrijf','w','kleine klus, klusjesdienst'],
  ['kapotte dakpan','w','één pan vervangen'],
  ['gebroken dakpan','w','één pan vervangen'],
  ['losse dakpan','w','één pan vervangen'],
  ['dakpan vervangen','w','één pan vervangen'],
  ['verschoven','w','pannen terugleggen'],
  ['afgewaaid','w','pannen terugleggen na storm'],
  ['afgewaaide','w','pannen terugleggen na storm'],
  ['omhoog schuiven','w','pannen verleggen, doe-het-zelf'],
  ['nokpannen','w','noklijn herstellen, kleine klus'],
  ['nokpan','w','noklijn herstellen, kleine klus'],
  ['nokvorst','w','noklijn herstellen, kleine klus'],
  ['nokvorsten','w','noklijn herstellen, kleine klus'],
  ['aansmeren','w','noklijn herstellen, kleine klus'],
  ['dakgoot vervangen','w','losse goot, geen dak'],
  ['dakgoten vervangen','w','losse goot, geen dak'],
  ['goot vervangen','w','losse goot, geen dak'],
  ['goten vervangen','w','losse goot, geen dak'],
  ['dakgoot plaatsen','w','losse goot, geen dak'],
  ['dakgoten plaatsen','w','losse goot, geen dak'],
  ['zinken dakgoot','w','losse goot, geen dak'],
  ['zinken goot','w','losse goot, geen dak'],
  ['pvc goot','w','losse goot, geen dak'],
  ['pvc dakgoot','w','losse goot, geen dak'],
  ['hanggoot','w','losse goot, geen dak'],
  ['hanggoten','w','losse goot, geen dak'],
  ['mastgoot','w','losse goot, geen dak'],
  ['kilgoot','w','kilgoot herstellen, kleine klus'],
  ['kilgoten','w','kilgoot herstellen, kleine klus'],
  ['regenpijp','w','afvoerpijp, kleine klus'],
  ['regenpijpen','w','afvoerpijp, kleine klus'],
  ['afvoerpijp','w','afvoerpijp, kleine klus'],
  ['bladvanger','w','goot-accessoire, kleine klus'],
  ['gootbeugels','w','goot-accessoire, kleine klus'],
  ['ruimen','w','goot ruimen, onderhoud'],
  ['mos','w','ontmossen, onderhoud'],
  ['ontmossen','w','ontmossen, onderhoud'],
  ['ontmossing','w','ontmossen, onderhoud'],
  ['mosvrij','w','ontmossen, onderhoud'],
  ['reinigen','w','dakreiniging, onderhoud'],
  ['reiniging','w','dakreiniging, onderhoud'],
  ['dakreiniging','w','dakreiniging, onderhoud'],
  ['schoonmaken','w','dakreiniging, onderhoud'],
  ['schoonspuiten','w','dakreiniging, onderhoud'],
  ['kuisen','w','dakreiniging, onderhoud'],
  ['hogedruk','w','dakreiniging, onderhoud'],
  ['hogedrukreiniger','w','dakreiniging, onderhoud'],
  ['coating','w','coating = alternatief voor vernieuwen'],
  ['coaten','w','coating = alternatief voor vernieuwen'],
  ['dakcoating','w','coating = alternatief voor vernieuwen'],
  ['impregneren','w','impregnatie, onderhoud'],
  ['impregnatie','w','impregnatie, onderhoud'],
  ['verven','w','dak schilderen, onderhoud of doe-het-zelf'],
  ['schilderen','w','dak schilderen, onderhoud of doe-het-zelf'],
  ['wit maken','w','plat dak koelen, doe-het-zelf'],
  ['schouwveger','w','schouw vegen, andere dienst'],
  ['schoorsteenveger','w','schouw vegen, andere dienst'],
  ['schouw vegen','w','schouw vegen, andere dienst'],
  ['schoorsteen vegen','w','schouw vegen, andere dienst'],
  ['schouwkap','w','schouwkap, kleine klus'],
  ['schoorsteenkap','w','schouwkap, kleine klus'],
  ['schouw voegen','w','schouw voegen, kleine klus'],
  ['schoorsteen voegen','w','schouw voegen, kleine klus'],
  ['rookkanaal','w','schouw/kachel, andere dienst'],
  ['loodslab','w','loodwerk herstellen, kleine klus'],
  ['loodslabben','w','loodwerk herstellen, kleine klus'],
  ['loodstrip','w','loodwerk herstellen, kleine klus'],
  ['loodschort','w','loodwerk herstellen, kleine klus'],
  ['velux plaatsen','w','één dakraam onder 5.000 euro'],
  ['velux laten plaatsen','w','één dakraam onder 5.000 euro'],
  ['velux vervangen','w','één dakraam onder 5.000 euro'],
  ['velux dakraam','w','één dakraam onder 5.000 euro'],
  ['velux prijs','w','één dakraam onder 5.000 euro'],
  ['prijs velux','w','één dakraam onder 5.000 euro'],
  ['dakraam plaatsen','w','één dakraam onder 5.000 euro'],
  ['dakraam vervangen','w','één dakraam onder 5.000 euro'],
  ['dakramen plaatsen','w','dakramen zonder dakwerk'],
  ['dakramen vervangen','w','dakramen zonder dakwerk'],
  ['dakraam prijs','w','één dakraam onder 5.000 euro'],
  ['prijs dakraam','w','één dakraam onder 5.000 euro'],
  ['dakvenster plaatsen','w','één dakraam onder 5.000 euro'],
  ['dakvenster vervangen','w','één dakraam onder 5.000 euro'],
  ['dakvensters plaatsen','w','dakramen zonder dakwerk'],
  ['dakvensters vervangen','w','dakramen zonder dakwerk'],
  ['fakro plaatsen','w','één dakraam onder 5.000 euro'],
  ['dakraampje','w','klein dakraam, kleine klus'],
  ['lichtkoepel vervangen','w','losse lichtkoepel, kleine klus'],
  ['lichtkoepel plaatsen','w','losse lichtkoepel, kleine klus'],
  ['lichtstraat plaatsen','w','losse lichtstraat, kleine klus'],
  ['rolgordijn','w','dakraam-accessoire'],
  ['zonwering','w','dakraam-accessoire'],
  ['verduisterend','w','dakraam-accessoire'],
  ['verduistering','w','dakraam-accessoire'],
  ['rolluik','w','dakraam-accessoire'],
  ['hor','w','dakraam-accessoire'],
  ['horren','w','dakraam-accessoire'],
  ['vliegenraam','w','dakraam-accessoire'],
  ['sk06','w','Velux-maatcode = één raam'],
  ['mk04','w','Velux-maatcode = één raam'],
  ['mk06','w','Velux-maatcode = één raam'],
  ['uk04','w','Velux-maatcode = één raam'],
  ['ck02','w','Velux-maatcode = één raam'],
  ['boeiboord','w','boeiboord, kleine klus'],
  ['boeiboorden','w','boeiboord, kleine klus'],
  ['boeidelen','w','boeiboord, kleine klus'],
  ['windveer','w','windveer, kleine klus'],
  ['windveren','w','windveer, kleine klus'],
  ['daktrim','w','dakrandprofiel, kleine klus'],
  ['doorvoer','w','dakdoorvoer plaatsen, kleine klus'],
  ['dakdoorvoer','w','dakdoorvoer plaatsen, kleine klus'],
  ['kabeldoorvoer','w','dakdoorvoer plaatsen, kleine klus'],
  ['airco','w','airco-doorvoer, andere dienst'],
  ['ontluchting','w','ontluchtingspan, kleine klus'],
  ['ontluchtingspijp','w','ontluchtingspan, kleine klus'],
  ['antenne','w','antenne, andere dienst'],
  ['schotelantenne','w','antenne, andere dienst'],
  ['bliksemafleider','w','bliksemafleider, andere dienst'],
  ['vogelwering','w','ongedierte, kleine klus'],
  ['vogels','w','ongedierte, kleine klus'],
  ['duiven','w','ongedierte, kleine klus'],
  ['marter','w','ongedierte, kleine klus'],
  ['steenmarter','w','ongedierte, kleine klus'],
  ['binnenkant','w','isolatie langs binnen, geen dakwerk'],
  ['binnenzijde','w','isolatie langs binnen, geen dakwerk'],
  ['binnenuit','w','isolatie langs binnen, geen dakwerk'],
  ['langs binnen','w','isolatie langs binnen, geen dakwerk'],
  ['plafond','w','binnenafwerking, geen dakwerk'],
  ['gyproc','w','binnenafwerking, geen dakwerk'],
  ['gipsplaten','w','binnenafwerking, geen dakwerk'],
  ['stucen','w','binnenafwerking, geen dakwerk'],
  ['pleisteren','w','binnenafwerking, geen dakwerk'],
  ['underlayment','w','doe-het-zelf materiaal'],
  ['osb','w','doe-het-zelf materiaal'],
  ['montagesysteem','w','zonnepaneelmontage, andere dienst'],
  ['beugels','w','zonnepaneelmontage of goot-accessoire'],
  ['warmtepomp','w','andere dienst (warmtepomp op dak)'],
  ['kachel','w','kachelpijp-doorvoer, andere dienst'],
  ['houtkachel','w','kachelpijp-doorvoer, andere dienst'],
  ['cv ketel','w','ketel-doorvoer, andere dienst'],
  ['rookgasafvoer','w','ketel-doorvoer, andere dienst'],
  ['drone','w','drone-inspectie of reiniging'],
];
K['2 Bijgebouwen'] = [
  ['garage','w','garagedak, onder 5.000 euro'],
  ['garages','w','garagedak, onder 5.000 euro'],
  ['garagedak','w','garagedak, onder 5.000 euro'],
  ['carport','w','bijgebouw, kleine klus'],
  ['tuinhuis','w','bijgebouw, kleine klus'],
  ['tuinhuisje','w','bijgebouw, kleine klus'],
  ['blokhut','w','bijgebouw, kleine klus'],
  ['schuur','w','bijgebouw, kleine klus'],
  ['schuurtje','w','bijgebouw, kleine klus'],
  ['berging','w','bijgebouw, kleine klus'],
  ['tuinberging','w','bijgebouw, kleine klus'],
  ['fietsenberging','w','bijgebouw, kleine klus'],
  ['veranda','w','bijgebouw, kleine klus'],
  ['overkapping','w','bijgebouw, kleine klus'],
  ['terrasoverkapping','w','bijgebouw, kleine klus'],
  ['afdak','w','bijgebouw, kleine klus'],
  ['afdakje','w','bijgebouw, kleine klus'],
  ['luifel','w','bijgebouw, kleine klus'],
  ['pergola','w','bijgebouw, kleine klus'],
  ['poolhouse','w','bijgebouw, kleine klus'],
  ['serre','w','bijgebouw, kleine klus'],
  ['chalet','w','bijgebouw of vakantiewoning'],
  ['kippenhok','w','bijgebouw, kleine klus'],
  ['houthok','w','bijgebouw, kleine klus'],
  ['hok','w','bijgebouw, kleine klus'],
  ['bijgebouw','w','bijgebouw, onder 5.000 euro'],
  ['polycarbonaat','w','veranda/carportplaat, geen woningdak'],
  ['dakplaten','w','platen voor bijgebouw of doe-het-zelf'],
  ['dakpanplaten','w','platen voor bijgebouw of doe-het-zelf'],
  ['onduline','w','platen voor bijgebouw of doe-het-zelf'],
];
K['3 Doe-het-zelf en info'] = [
  ['zelf','w','doe-het-zelver'],
  ['doe het zelf','w','doe-het-zelver'],
  ['hoe maak je','w','doe-het-zelver'],
  ['hoe leg je','w','doe-het-zelver'],
  ['hoe plaats je','w','doe-het-zelver'],
  ['hoe dakpannen leggen','w','doe-het-zelver'],
  ['hoe roofing leggen','w','doe-het-zelver'],
  ['hoe epdm leggen','w','doe-het-zelver'],
  ['in het frans','w','vertaalvraag'],
  ['diy','w','doe-het-zelver'],
  ['handleiding','w','doe-het-zelver'],
  ['stappenplan','w','doe-het-zelver'],
  ['tutorial','w','doe-het-zelver'],
  ['uitleg','w','infozoeker'],
  ['youtube','w','infozoeker, video'],
  ['video','w','infozoeker, video'],
  ['filmpje','w','infozoeker, video'],
  ['wikipedia','w','infozoeker'],
  ['betekenis','w','infozoeker'],
  ['definitie','w','infozoeker'],
  ['gewicht','w','technische info'],
  ['dikte','w','technische info'],
  ['graden','w','technische info (helling)'],
  ['hellingshoek','w','technische info (helling)'],
  ['detail','w','technische tekening, architect/student'],
  ['details','w','technische tekening, architect/student'],
  ['doorsnede','w','technische tekening, architect/student'],
  ['dwg','w','technische tekening, architect/student'],
  ['tekening','w','technische tekening of kindertekening'],
  ['tekenen','w','technische tekening of kindertekening'],
  ['bouwknoop','w','technische info'],
  ['wtcb','w','technische info (Buildwise)'],
  ['buildwise','w','technische info'],
  ['pdf','w','infozoeker, document'],
  ['engels','w','vertaalvraag'],
  ['vertaling','w','vertaalvraag'],
  ['english','w','vertaalvraag'],
  ['francais','w','vertaalvraag'],
  ['letters','w','kruiswoordraadsel'],
  ['puzzel','w','kruiswoordraadsel'],
  ['kruiswoordraadsel','w','kruiswoordraadsel'],
  ['sims','w','computerspel'],
  ['minecraft','w','computerspel'],
  ['klachten','w','klacht over bestaande firma'],
  ['failliet','w','nieuws over firma'],
  ['faillissement','w','nieuws over firma'],
  ['in gebreke','w','geschil met bestaande aannemer'],
  ['advocaat','w','geschil met bestaande aannemer'],
  ['rechtbank','w','geschil met bestaande aannemer'],
  ['kadastraal','w','fiscale info na werken'],
  ['afkoelen','w','plat dak koelen, info'],
  ['koelen','w','plat dak koelen, info'],
  ['hitte','w','plat dak koelen, info'],
  ['asbestattest','w','attest door asbestdeskundige, andere dienst'],
  ['asbestinventaris','w','attest door asbestdeskundige, andere dienst'],
  ['asbestinventarisatie','w','attest door asbestdeskundige, andere dienst'],
  ['asbestdeskundige','w','attest door asbestdeskundige, andere dienst'],
  ['herkennen','w','infozoeker (asbest herkennen)'],
  ['asbestzak','w','zelf asbest afvoeren'],
  ['asbestzakken','w','zelf asbest afvoeren'],
  ['ophaling','w','zelf afval afvoeren'],
  ['containerpark','w','zelf afval afvoeren'],
  ['recyclagepark','w','zelf afval afvoeren'],
  ['afvalpark','w','zelf afval afvoeren'],
];
K['4 Jobs en opleiding'] = [
  ['vacature','w','werkzoekende'],
  ['vacatures','w','werkzoekende'],
  ['job','w','werkzoekende'],
  ['jobs','w','werkzoekende'],
  ['jobstudent','w','werkzoekende'],
  ['studentenjob','w','werkzoekende'],
  ['flexijob','w','werkzoekende'],
  ['werken als','w','werkzoekende'],
  ['werken bij','w','werkzoekende'],
  ['sollicitatie','w','werkzoekende'],
  ['solliciteren','w','werkzoekende'],
  ['dakwerker worden','w','beroepskeuze'],
  ['dakdekker worden','w','beroepskeuze'],
  ['zelfstandig worden','w','beroepskeuze'],
  ['loon','w','werkzoekende'],
  ['lonen','w','werkzoekende'],
  ['uurloon','w','werkzoekende of prijs kleine klus'],
  ['uurtarief','w','prijs kleine klus of werkzoekende'],
  ['per uur','w','prijs kleine klus of werkzoekende'],
  ['salaris','w','werkzoekende'],
  ['verdienen','w','werkzoekende'],
  ['brutoloon','w','werkzoekende'],
  ['nettoloon','w','werkzoekende'],
  ['cao','w','werkzoekende'],
  ['paritair','w','werkzoekende'],
  ['opleiding','w','opleiding'],
  ['opleidingen','w','opleiding'],
  ['cursus','w','opleiding'],
  ['stage','w','opleiding'],
  ['stageplaats','w','opleiding'],
  ['leercontract','w','opleiding'],
  ['duaal leren','w','opleiding'],
  ['syntra','w','opleiding'],
  ['vdab','w','opleiding of vacature'],
  ['cvo','w','opleiding'],
  ['bbl','w','opleiding (Nederland)'],
  ['mbo','w','opleiding (Nederland)'],
  ['interim','w','uitzendwerk'],
  ['uitzendkantoor','w','uitzendwerk'],
  ['uitzendbureau','w','uitzendwerk'],
  ['onderaanneming','w','onderaannemer zoekt werk'],
  ['onderaannemer','w','onderaannemer zoekt werk'],
  ['vca','w','attest werkzoekende'],
  ['nace','w','administratie ondernemer'],
  ['hiring','w','werkzoekende (Engels)'],
  ['dakwerkerskraan','w','materieel voor vakmensen'],
  ['hoogwerker','w','materieel huren'],
  ['steiger huren','w','materieel huren'],
  ['valbeveiliging','w','materieel voor vakmensen'],
  ['ankerpunt','w','materieel voor vakmensen'],
  ['ladder','w','materieel, doe-het-zelf'],
  ['ladderlift','w','materieel voor vakmensen'],
  ['huren','w','materieel huren'],
];
K['5 Materiaal kopen en handel'] = [
  ['dakpannen kopen','w','materiaalkoper'],
  ['dakpan kopen','w','materiaalkoper'],
  ['nokpannen kopen','w','materiaalkoper'],
  ['leien kopen','w','materiaalkoper'],
  ['dakleien kopen','w','materiaalkoper'],
  ['roofing kopen','w','materiaalkoper'],
  ['epdm kopen','w','materiaalkoper'],
  ['bitumen kopen','w','materiaalkoper'],
  ['isolatie kopen','w','materiaalkoper'],
  ['isolatieplaten kopen','w','materiaalkoper'],
  ['velux kopen','w','materiaalkoper'],
  ['dakraam kopen','w','materiaalkoper'],
  ['golfplaten kopen','w','materiaalkoper'],
  ['sandwichpanelen kopen','w','materiaalkoper'],
  ['shingles kopen','w','materiaalkoper'],
  ['bestellen','w','materiaalkoper'],
  ['webshop','w','materiaalkoper'],
  ['te koop','w','materiaal of vastgoed te koop'],
  ['gamma','w','doe-het-zelfzaak'],
  ['brico','w','doe-het-zelfzaak'],
  ['hubo','w','doe-het-zelfzaak'],
  ['praxis','w','doe-het-zelfzaak (Nederland)'],
  ['hornbach','w','doe-het-zelfzaak'],
  ['karwei','w','doe-het-zelfzaak (Nederland)'],
  ['bouwmaat','w','handel (Nederland)'],
  ['leroy merlin','w','doe-het-zelfzaak'],
  ['bouwmarkt','w','doe-het-zelfzaak'],
  ['groothandel','w','handel'],
  ['leverancier','w','handel'],
  ['leveranciers','w','handel'],
  ['verdeler','w','handel'],
  ['distributeur','w','handel'],
  ['per stuk','w','materiaalprijs'],
  ['per rol','w','materiaalprijs'],
  ['rol','w','materiaal op rol'],
  ['pallet','w','materiaalprijs'],
  ['tweedehands','w','materiaalkoper'],
  ['2dehands','w','materiaalkoper'],
  ['marktplaats','w','materiaalkoper (Nederland)'],
  ['occasie','w','materiaalkoper'],
  ['gebruikt','w','materiaalkoper'],
  ['gebruikte','w','materiaalkoper'],
  ['restpartij','w','materiaalkoper'],
  ['b keus','w','materiaalkoper'],
  ['kit','w','doe-het-zelf materiaal'],
  ['bitumenkit','w','doe-het-zelf materiaal'],
  ['lijm','w','doe-het-zelf materiaal'],
  ['lijmen','w','doe-het-zelf materiaal'],
  ['tape','w','doe-het-zelf materiaal'],
  ['primer','w','doe-het-zelf materiaal'],
  ['brander','w','doe-het-zelf materiaal'],
  ['mastiek','w','doe-het-zelf materiaal'],
  ['reparatieset','w','doe-het-zelf materiaal'],
  ['pakket','w','doe-het-zelf materiaal'],
  ['bouwpakket','w','doe-het-zelf materiaal'],
  ['zelfklevend','w','doe-het-zelf materiaal'],
  ['vijverfolie','w','ander product'],
  ['aquaplan','w','doe-het-zelf verfproduct'],
  ['tec7','w','doe-het-zelf product'],
  ['rust-oleum','w','doe-het-zelf product'],
  ['maten','w','materiaalmaten, koper'],
  ['afmetingen','w','materiaalmaten, koper'],
];
K['6 B2B, grote bouw, andere doelgroep'] = [
  ['industrie','w','industrieel dak, geen woning'],
  ['industrieel','w','industrieel dak, geen woning'],
  ['industriedak','w','industrieel dak, geen woning'],
  ['industriebouw','w','industrieel dak, geen woning'],
  ['loods','w','loods, geen woning'],
  ['loodsen','w','loods, geen woning'],
  ['hangar','w','loods, geen woning'],
  ['magazijn','w','bedrijfsgebouw, geen woning'],
  ['fabriek','w','bedrijfsgebouw, geen woning'],
  ['bedrijfsgebouw','w','bedrijfsgebouw, geen woning'],
  ['bedrijfspand','w','bedrijfsgebouw, geen woning'],
  ['stal','w','landbouwgebouw, geen woning'],
  ['stallen','w','landbouwgebouw, geen woning'],
  ['paardenstal','w','landbouwgebouw, geen woning'],
  ['landbouw','w','landbouwgebouw, geen woning'],
  ['aanbesteding','w','overheidsopdracht'],
  ['overheidsopdracht','w','overheidsopdracht'],
  ['sociale woning','w','sociale huisvesting, geen eigenaar'],
  ['sociale huur','w','sociale huisvesting, geen eigenaar'],
  ['sociale huisvesting','w','sociale huisvesting, geen eigenaar'],
  ['huisvestingsmaatschappij','w','sociale huisvesting, geen eigenaar'],
  ['woonmaatschappij','w','sociale huisvesting, geen eigenaar'],
  ['nieuw dak genk','w','sociale huisvestingsmaatschappij Nieuw Dak'],
  ['kolderbos','w','sociale huisvestingsmaatschappij Nieuw Dak'],
  ['cvba','w','sociale huisvestingsmaatschappij Nieuw Dak'],
  ['wachtlijst','w','sociale huisvesting'],
  ['technische dienst','w','sociale huisvesting'],
  ['huurder','w','huurder, geen eigenaar'],
  ['huurwoning','w','huurder, geen eigenaar'],
  ['huurwoningen','w','huurder, geen eigenaar'],
  ['te huur','w','vastgoedzoeker'],
  ['dakappartement','w','vastgoedzoeker'],
  ['immoweb','w','vastgoedzoeker'],
  ['zimmo','w','vastgoedzoeker'],
];
K['7 Concurrenten bij naam'] = [
  ['kijzer','w','concurrent (top 5 adverteerder)'],
  ['dural','w','concurrent (top 5 adverteerder)'],
  ['recotex','w','concurrent (top 5 adverteerder)'],
  ['rinovato','w','concurrent (top 5)'],
  ['facibel','w','concurrent (merk achter Rinovato)'],
  ['verelst','w','concurrent (top 5)'],
  ['tifre','w','concurrent (al in gedeelde lijst)'],
  ['klussenier','w','concurrent, klusjesfranchise'],
  ['homedeal','w','offerteplatform'],
  ['bobex','w','offerteplatform'],
  ['werkspot','w','offerteplatform'],
  ['trustlocal','w','offerteplatform'],
  ['trustup','w','offerteplatform'],
  ['aannemeroffertes','w','offerteplatform'],
  ['offerteadvies','w','offerteplatform'],
  ['aa dakwerken','w','concurrent regio Antwerpen'],
  ['antwerpse algemene dakwerken','w','concurrent regio Antwerpen'],
  ['zekerdak','w','concurrent regio Antwerpen'],
  ['speelman','w','concurrent regio Antwerpen'],
  ['asfaltroof','w','concurrent regio Antwerpen'],
  ['rvo construct','w','concurrent regio Antwerpen'],
  ['ft dakrenovatie','w','concurrent regio Antwerpen'],
  ['vd build','w','concurrent (SERP-advertentie dakwerken)'],
  ['naessens','w','concurrent (autocomplete dakwerken)'],
  ['devidt','w','concurrent (autocomplete dakwerken)'],
  ['apers','w','concurrent (autocomplete dakwerken)'],
  ['hendrickx','w','concurrent (autocomplete dakwerken)'],
  ['scv','w','concurrent (autocomplete dakwerken)'],
  ['adriaens','w','concurrent (autocomplete dakwerken)'],
  ['vaneeckhoutte','w','concurrent (autocomplete dakwerken)'],
  ['brems','w','concurrent (autocomplete dakwerken)'],
  ['bruneel','w','concurrent (autocomplete dakwerken)'],
  ['boets','w','concurrent (autocomplete dakwerken)'],
  ['crabbe','w','concurrent (autocomplete dakwerken)'],
  ['cauwelier','w','concurrent (autocomplete dakwerken)'],
  ['casier','w','concurrent (autocomplete dakwerken)'],
  ['coppens','w','concurrent (autocomplete dakwerken)'],
  ['debrabandere','w','concurrent (autocomplete dakwerken)'],
  ['demeyer','w','concurrent (autocomplete dakwerken)'],
  ['desmet','w','concurrent (autocomplete dakwerken)'],
  ['de donder','w','concurrent (autocomplete dakwerken)'],
  ['elewaut','w','concurrent (autocomplete dakwerken)'],
  ['feys','w','concurrent (autocomplete dakwerken)'],
  ['franssen','w','concurrent (autocomplete dakwerken)'],
  ['van hecke','w','concurrent (autocomplete dakwerken)'],
  ['bauters','w','concurrent (autocomplete dakwerken)'],
  ['feyaerts','w','concurrent (autocomplete dakwerken)'],
  ['gielen','w','concurrent (autocomplete dakwerken)'],
  ['geens','w','concurrent (autocomplete dakwerken)'],
  ['goethals','w','concurrent (autocomplete dakwerken)'],
  ['goddé','w','concurrent (autocomplete dakwerken)'],
  ['hemerijckx','w','concurrent (autocomplete dakwerken)'],
  ['holemans','w','concurrent (autocomplete dakwerken)'],
  ['isenborghs','w','concurrent (autocomplete dakwerken)'],
  ['jennes','w','concurrent (autocomplete dakwerken)'],
  ['jonckheere','w','concurrent (autocomplete dakwerken)'],
  ['keppens','w','concurrent (autocomplete dakwerken)'],
  ['lauryssen','w','concurrent (autocomplete dakwerken)'],
  ['meynen','w','concurrent (autocomplete dakwerken)'],
  ['meeus','w','concurrent (autocomplete dakwerken)'],
  ['moerman','w','concurrent (autocomplete dakwerken)'],
  ['maenhaut','w','concurrent (autocomplete dakwerken)'],
  ['nauwelaerts','w','concurrent (autocomplete dakwerken)'],
  ['nuyts','w','concurrent (autocomplete dakwerken)'],
  ['op de beeck','w','concurrent (autocomplete dakwerken)'],
  ['parmentier','w','concurrent (autocomplete dakwerken)'],
  ['peetermans','w','concurrent (autocomplete dakwerken)'],
  ['quintyn','w','concurrent (autocomplete dakwerken)'],
  ['quartel','w','concurrent (autocomplete dakwerken)'],
  ['roels','w','concurrent (autocomplete dakwerken)'],
  ['schollier','w','concurrent (autocomplete dakwerken)'],
  ['stockman','w','concurrent (autocomplete dakwerken)'],
  ['stoffels','w','concurrent (autocomplete dakwerken)'],
  ['theuwissen','w','concurrent (autocomplete dakwerken)'],
  ['umans','w','concurrent (autocomplete dakwerken)'],
  ['uytterhaegen','w','concurrent (autocomplete dakwerken)'],
  ['verschuere','w','concurrent (autocomplete dakwerken)'],
  ['van den driessche','w','concurrent (autocomplete dakwerken)'],
  ['vanhoudt','w','concurrent (autocomplete dakwerken)'],
  ['verstrepen','w','concurrent (autocomplete dakwerken)'],
  ['vannes','w','concurrent (autocomplete dakwerken)'],
  ['vermeersch','w','concurrent (autocomplete dakwerken)'],
  ['van tongerloo','w','concurrent (autocomplete dakwerken)'],
  ['willemsen','w','concurrent (autocomplete dakwerken)'],
  ['willaert','w','concurrent (autocomplete dakwerken)'],
  ['xada','w','concurrent (autocomplete dakwerken)'],
  ['xteria','w','concurrent (autocomplete dakwerken)'],
  ['xcover','w','concurrent (autocomplete dakwerken)'],
  ['verboven','w','concurrent (autocomplete dakwerken)'],
  ['eeckhout','w','concurrent (autocomplete dakwerken)'],
  ['cooreman','w','concurrent (autocomplete dakwerken)'],
  ['van daele','w','concurrent (autocomplete dakwerken)'],
  ['ysewijn','w','concurrent (autocomplete dakwerken)'],
  ['zwaenepoel','w','concurrent (autocomplete dakwerken)'],
  ['plaetinck','w','concurrent (autocomplete dakwerker)'],
  ['cuylaerts','w','concurrent (autocomplete dakwerker)'],
  ['cortebeeck','w','concurrent (autocomplete dakwerker)'],
  ['noterman','w','concurrent (autocomplete dakwerker)'],
  ['van beijnen','w','concurrent (autocomplete dakwerker)'],
  ['uniek dakwerken','w','concurrent (autocomplete dakwerken)'],
  ['quantum dakwerken','w','concurrent (autocomplete dakwerken)'],
  ['david en zoon','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken jacobs','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken wouters','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken claes','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken cools','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken smets','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken franken','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken peeters','w','concurrent (autocomplete dakwerken)'],
  ['dakwerken janssens','w','concurrent (autocomplete dakwerken)'],
];
K['8 Nederland'] = [
  ['nederland','w','Nederlandse zoeker'], ['holland','w','Nederlandse zoeker'], ['nl','w','Nederlandse zoeker'],
  ['isde','w','Nederlandse subsidie'], ['vve','w','Nederlandse vereniging van eigenaren'],
  ['9 btw','w','Nederlands btw-tarief'], ['vergunningsvrij','w','Nederlandse regelterm'],
  ['noord holland','w','Nederlandse provincie'], ['zuid holland','w','Nederlandse provincie'], ['noord brabant','w','Nederlandse provincie'],
  ['friesland','w','Nederlandse provincie'], ['drenthe','w','Nederlandse provincie'], ['overijssel','w','Nederlandse provincie'],
  ['gelderland','w','Nederlandse provincie'], ['flevoland','w','Nederlandse provincie'], ['zeeland','w','Nederlandse provincie'],
  ['zeeuws vlaanderen','w','Nederlandse regio'], ['zuid limburg','w','Nederlandse regio'], ['twente','w','Nederlandse regio'], ['randstad','w','Nederlandse regio'], ['achterhoek','w','Nederlandse regio'], ['westland','w','Nederlandse regio'],
  ['amsterdam','w','Nederlandse stad'], ['rotterdam','w','Nederlandse stad'], ['den haag','w','Nederlandse stad'], ['utrecht','w','Nederlandse stad'],
  ['eindhoven','w','Nederlandse stad'], ['groningen','w','Nederlandse stad'], ['tilburg','w','Nederlandse stad'], ['almere','w','Nederlandse stad'],
  ['breda','w','Nederlandse stad, grensregio'], ['nijmegen','w','Nederlandse stad'], ['apeldoorn','w','Nederlandse stad'], ['arnhem','w','Nederlandse stad'],
  ['haarlem','w','Nederlandse stad'], ['enschede','w','Nederlandse stad'], ['amersfoort','w','Nederlandse stad'], ['zaandam','w','Nederlandse stad'],
  ['den bosch','w','Nederlandse stad'], ['zwolle','w','Nederlandse stad'], ['leiden','w','Nederlandse stad'], ['dordrecht','w','Nederlandse stad'],
  ['zoetermeer','w','Nederlandse stad'], ['maastricht','w','Nederlandse stad'], ['deventer','w','Nederlandse stad'], ['alkmaar','w','Nederlandse stad'],
  ['hilversum','w','Nederlandse stad'], ['helmond','w','Nederlandse stad'], ['venlo','w','Nederlandse stad'], ['leeuwarden','w','Nederlandse stad'],
  ['roosendaal','w','Nederlandse stad, grensregio'], ['bergen op zoom','w','Nederlandse stad, grensregio'], ['hulst','w','Nederlandse stad, grensregio'], ['terneuzen','w','Nederlandse stad, grensregio'],
  ['zundert','w','Nederlandse gemeente, grensregio'], ['woensdrecht','w','Nederlandse gemeente, grensregio'], ['goes','w','Nederlandse stad'], ['middelburg','w','Nederlandse stad'],
  ['vlissingen','w','Nederlandse stad'], ['etten leur','w','Nederlandse stad, grensregio'], ['oosterhout','w','Nederlandse stad'], ['heerlen','w','Nederlandse stad'],
  ['sittard','w','Nederlandse stad'], ['roermond','w','Nederlandse stad'], ['mulder','w','Nederlandse dakfirma (autocomplete)'], ['hilberts','w','Nederlandse dakfirma (autocomplete)'],
  ['westra','w','Nederlandse dakfirma (autocomplete)'], ['hofstra','w','Nederlandse dakfirma (autocomplete)'], ['reinders','w','Nederlandse dakfirma (autocomplete)'], ['cantex','w','Nederlandse dakfirma (autocomplete)'],
  ['benelux','w','Nederlandse dakfirma (autocomplete)'], ['woningnet','w','Nederlandse woningcorporatie "Dak"'], ['studentenwoning','w','Nederlandse woningcorporatie "Dak"'], ['jongerenwoning','w','Nederlandse woningcorporatie "Dak"'],
  ['inloggen','w','woningcorporatie of klantenportaal'], ['inschrijven','w','woningcorporatie of wachtlijst'], ['inschrijving','w','woningcorporatie of wachtlijst'], ['urgentie','w','woningcorporatie'],
];
K['9 Ruis: andere betekenis van "dak"'] = [
  ['auto','w','autodak'], ['cabrio','w','autodak'], ['cabriolet','w','autodak'], ['schuifdak','w','autodak'], ['panoramadak','w','autodak'],
  ['dakkoffer','w','auto-accessoire'], ['dakdrager','w','auto-accessoire'], ['dakdragers','w','auto-accessoire'], ['dakrails','w','auto-accessoire'], ['daktent','w','auto-accessoire'],
  ['fietsendrager','w','auto-accessoire'], ['thule','w','auto-accessoire'], ['caravan','w','caravandak'], ['stacaravan','w','caravandak'], ['mobilhome','w','caravandak'], ['camper','w','camperdak'],
  ['tent','w','tentdak'], ['partytent','w','tentdak'], ['boot','w','bootdak'],
  ['daktarin','w','medicijn (schimmelcrème)'], ['vaccin','w','medisch (shingles = gordelroos)'], ['vaccine','w','medisch (shingles = gordelroos)'], ['gordelroos','w','medisch'],
  ['dakota','w','persoonsnaam/staat'], ['prescott','w','sporter Dak Prescott'], ['quarterback','w','sport'], ['sak yant','w','tatoeage'], ['tattoo','w','tatoeage'],
  ['galbi','w','gerecht'], ['burger','w','restaurant'], ['coffee','w','koffiebar'], ['koffie','w','koffiebar'],
  ['thuislozen','w','daklozenopvang'], ['daklozen','w','daklozenopvang'], ['daklozenopvang','w','daklozenopvang'], ['dakloos','w','daklozenopvang'],
  ['dakje','w','uitdrukking "leien dakje"'], ['notre dame','w','nieuws'], ['camp nou','w','nieuws'], ['stadion','w','nieuws'],
  ['schouwburg','w','theater'], ['schouwen duiveland','w','Nederlandse gemeente'], ['nemo','w','museum Amsterdam'],
  ['riet','w','rieten dak, geen AB-dienst'], ['rieten','w','rieten dak, geen AB-dienst'], ['rietdekker','w','rieten dak, geen AB-dienst'], ['rietendak','w','rieten dak, geen AB-dienst'],
];
module.exports = K;
